variables:
    REPO: trasioteam/teep-dev
    TEEP_DEV_DOCS_DIR: /home/user/teep-device/docs
    TEEP_DEV_PDF: teep-device.pdf
    TEEP_HTML_PKG: teep-device_readme_html.tar.gz

stages:
    - build
    - test

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

# Template for tamproto service
.tamproto_service: &tamproto_service
    before_script:
        - docker run --rm --name tamproto --detach ${REPO}:tamproto
        - TAMIP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' tamproto)
    after_script:
        - docker stop tamproto

# Job for tamproto
teep-dev-tamproto:
    variables:
        BRANCH: master
    stage: build
    tags:
        - shell115
    script:
        - docker build --build-arg BRANCH=${BRANCH} --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:tamproto ./tamproto/master
        - docker push ${REPO}:tamproto

# Job for doxygen
teep-dev-doxygen:
    variables:
        BRANCH: master
    tags:
        - shell117
    stage: build
    script:
        - docker pull trasioteam/taref-dev:doxygen
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:doxygen ./doxygen/${BRANCH}
        - docker push ${REPO}:doxygen
        - docker run --name $CI_PIPELINE_ID -d ${REPO}:doxygen
        - docker wait $CI_PIPELINE_ID
        - docker cp $CI_PIPELINE_ID:${TEEP_DEV_DOCS_DIR}/${TEEP_DEV_PDF} $CI_PROJECT_DIR/${TEEP_DEV_PDF}
        - docker cp $CI_PIPELINE_ID:${TEEP_DEV_DOCS_DIR}/${TEEP_HTML_PKG} $CI_PROJECT_DIR/${TEEP_HTML_PKG}
    artifacts:
        paths:
            - $CI_PROJECT_DIR/${TEEP_DEV_PDF}
            - $CI_PROJECT_DIR/${TEEP_HTML_PKG}
        expire_in: 1 week

# Job for sgx
teep-dev-sgx:
    <<: *tamproto_service
    variables:
        BRANCH: master
    tags:
        - shell115
    stage: test
    script:
        - docker pull trasioteam/taref-dev:sgx
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP=${TAMIP} --rm -t ${REPO}:sgx ./sgx/${BRANCH}
        - docker push ${REPO}:sgx

# Job for sgx, branch wip
teep-dev-sgx-wip:
    <<: *tamproto_service
    variables:
        BRANCH: cleanup-before-publish
    tags:
        - shell115
    stage: test
    script:
        - docker pull trasioteam/taref-dev:sgx-wip
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP=${TAMIP} --rm -t ${REPO}:sgx ./sgx/branch-wip
        - docker push ${REPO}:sgx-wip

# Job for optee
teep-dev-optee:
    <<: *tamproto_service
    variables:
        BRANCH: master
    tags:
        - shell117
    stage: test
    script:
        - docker pull trasioteam/taref-dev:optee
        - docker build --no-cache --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP=${TAMIP} --rm -t ${REPO}:optee ./optee/${BRANCH}
        - docker push ${REPO}:optee

# Job for optee, branch wip
teep-dev-optee-wip:
    <<: *tamproto_service
    variables:
        BRANCH: cleanup-before-publish
    tags:
        - shell117
    stage: test
    script:
        - docker pull trasioteam/taref-dev:optee-wip
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP=${TAMIP} --rm -t ${REPO}:optee ./optee/branch-wip
        - docker push ${REPO}:optee-wip

# Job for keystone
teep-dev-keystone:
    <<: *tamproto_service
    variables:
        BRANCH: master
    tags:
        - shell121
    stage: test
    script:
        - docker pull trasioteam/taref-dev:keystone
        - docker build --no-cache --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP=${TAMIP} --rm -t ${REPO}:keystone ./keystone/${BRANCH}
        - docker push ${REPO}:keystone

# Job for keystone, branch wip
teep-dev-keystone-wip:
    <<: *tamproto_service
    variables:
        BRANCH: cleanup-before-publish
    tags:
        - shell121
    stage: test
    script:
        - docker pull trasioteam/taref-dev:keystone-wip
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP=${TAMIP} --rm -t ${REPO}:keystone ./keystone/branch-wip
        - docker push ${REPO}:keystone-wip
