variables:
    REPO: trasioteam/teep-dev
    TEEP_DEV_DOCS_DIR: /home/user/teep-device/docs
    TEEP_DEV_PDF: teep-device.pdf
    DOCKER_TAMPROTO_IMAGE: docker.io/trasioteam/tamproto

.tamproto_service: &tamproto_service
    services:
        - name: ${DOCKER_TAMPROTO_IMAGE}:latest
          alias: tamproto


before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

teep-dev-doxygen:
    variables:
        BRANCH: suit-dev
    tags:
        - shell117
    script:
        - docker pull trasioteam/taref-dev:doxygen
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:doxygen ./doxygen/suit-dev
        - docker push ${REPO}:doxygen
        - docker run --name $CI_PIPELINE_ID -d ${REPO}:doxygen
        - docker wait $CI_PIPELINE_ID
        - docker cp $CI_PIPELINE_ID:${TEEP_DEV_DOCS_DIR}/${TEEP_DEV_PDF} $CI_PROJECT_DIR/${TEEP_DEV_PDF}
    artifacts:
        paths:
            - $CI_PROJECT_DIR/${TEEP_DEV_PDF}
        expire_in: 1 week

teep-dev-sgx:
    variables:
        BRANCH: suit-dev
    services:
        - name: docker.io/trasioteam/tamproto:latest
          alias: tamproto
    tags:
        - shell115
    script:
        - docker pull trasioteam/taref-dev:sgx
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:sgx ./sgx/suit-dev
        - docker push ${REPO}:sgx

teep-dev-optee:
    variables:
        BRANCH: suit-dev
    services:
        - name: docker.io/trasioteam/tamproto:latest
          alias: tamproto
    tags:
        - shell117
    script:
        - docker pull trasioteam/taref-dev:optee
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP="172.17.0.4" --rm -t ${REPO}:optee ./optee/suit-dev
        - docker push ${REPO}:optee

teep-dev-keystone:
    <<: *tamproto_service
    variables:
        BRANCH: suit-dev
    tags:
        - shell121
    script:
        - docker info
        - docker service ls
        - docker pull trasioteam/taref-dev:keystone
        - docker build --build-arg BRANCH=${BRANCH} --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg TAMIP="172.17.0.4" --rm -t ${REPO}:keystone ./keystone/suit-dev
        - docker push ${REPO}:keystone
